#!/usr/bin/env bash
#####################################
#                                   #
#    GitHub    : @nahian-adnan     #
#  﫥 Copyright : Exodia OS         #
#                                   #
#####################################

THEME='Catppuccin-Mocha-Standard-Maroon-dark'
ICONS='Pop'
FONT='Noto Sans 9'
CURSOR='Qogirr-dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
