#!/usr/bin/env bash

# Kill already running process
_ps=(mako xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
#xfce-polkit &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Launch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Changing themes/icons
#~/.config/hypr/scripts/gtkthemes &

# motrix 
motrix &
