#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get Volume
get_volume() {
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | head -n1 | awk -F ' ' '{print $5}')
    echo "$volume"
}

# Get icons
get_icon() {
    vol="$(get_volume)"
    current="${vol%%%}"
    if [[ "$current" -eq "0" ]]; then
        icon="$iDIR/volume-mute.png"
    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        icon="$iDIR/volume-low.png"
    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        icon="$iDIR/volume-mid.png"
    elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
        icon="$iDIR/volume-high.png"
    fi
}

# Notify
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Volume : $(get_volume)"
}

# Increase Volume
inc_volume() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ -l 1.2
}

# Decrease Volume
dec_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
}

# Toggle Mute
toggle_mute() {
    pactl get-sink-volume | grep '\[on\]' &>/dev/null
    if [[ "$?" == 0 ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle 
    else
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    fi
}

# # Toggle Mic
toggle_mic() {
    amixer get Capture | grep '\[on\]' &>/dev/null
    if [[ "$?" == 0 ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle 
    else
        wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
    toggle_mic
else
    get_volume
fi
